---
author:
  - name: Carson Slater
    url: https://carsonslater.github.io
    phone: +1.480.320.8898
    email: "carsonslater7@gmail.com"
    affiliations:
      - name: Baylor University
        department: Department of Statistical Science
    title: "Research Assistant"
date: today
csl: "revsort-chicago-author-date.csl"
bibliography:
  books: "books.bib"
  bookchapters: "book_chapters.bib"
  articles: "journal_articles.bib"
nocite: '@*'
format:
  cv-typst:
    keep-typ: false
    linkcolor: "#154734"
    include-in-header: 
      - text: |
          #show regex("Slater"): strong
          #show regex("Carson"): strong
---

## Summary

Aspiring data scientist who loves to use statistical methods to empower people with insights for good stewardship.

## Education

{{< cv education >}}

## Employment

{{< cv appointments education.yaml >}}

<!-- {{< cv positions positions.yaml >}} -->

## Peer-Reviewed Works

:::{#refs-articles}
:::

## Projects

**Forecasting Fast-Moving Consumer Good Demand With Generalized Additive Models** [Link to Github](https://github.com/carsonslater/mentored_research2022)

- Built time-series forecasting models to predict quantity-demanded for fast-moving consumer goods in Indonesia.
- Presented poster at University of Illinois – Chicago’s 2022 Undergraduate Mathematics Symposium and Wheaton College’s 2022 Homecoming STEM Poster Session.

**Understanding and Modeling Predictors to Earned Run Average in Modern Major League Baseball**

- Conducted variable selection using predictors from the Lahman baseball database to model Earned Run Average using regression analysis. Used the same predictors to build a single-layer neural network and a radial support vector regression model in R/RStudio.

## Skills

**Technology**: Docker, Positron ($\approx$ VS Code), Git/Github, reveal.js, R/RStudio, SQL, duckDB, LaTeX.

**Python**: pandas, numpy, PyTorch (Lightning), plotnine, seaborn, plotly, scikit‑learn, Jupyter

**R**: tidyverse (dplyr, ggplot2, etc.), TensorFlow (Keras), torch, shiny, RMarkdown/Quarto, rstan, rjags, caret, tidymodels, targets (gittargets, proffer, etc.)

**Statistics and Machine Learning**: statistical modeling, hypothesis testing, mixture models, time series, regression, linear mixed models, clustering, classification, deep learning, PCA, random forests, ensemble models (e.g., XGBoost), SVM, Bayesian methods, spatiotemporal modeling

**Relevant Coursework**: Statistical Bioinformatics, Deep Learning, Bayesian Methods, Bayesian Theory, Survival Analysis, Time Series, Theory of Statistics, Statistical Methods, Computational Statistics, Numerical Analysis, Linear Algebra for Data Analysis, Mathematical Statistics, Machine Learning, Probability Theory, Real Analysis, Intensive Introduction to Computer Science (*Harvard*), Econometrics, Economics of Labor and Poverty.

## Honors & Awards

{{< cv honors >}}

## Service & Volunteer

{{< cv positions >}}
